### ISSUE TITLE
error in elb_http.tf when "terraform plan"

### ISSUE THREAD

**Issue by elzinko** [nextrevision/terraform-rancher-ha-example#5]
ERROR when terraform plan
=======================

Error running plan: 1 error(s) occurred:
* aws_proxy_protocol_policy.rancher_ha_http_proxy_policy: 1 error(s) occurred:
* aws_proxy_protocol_policy.rancher_ha_http_proxy_policy: Resource 'aws_elb.rancher_ha_https' not found for variable 'aws_elb.rancher_ha_https.name'

FIX
===

In elb_http.tf, replace

```
resource "aws_proxy_protocol_policy" "rancher_ha_http_proxy_policy" {
    count          = "${1 - var.enable_https}"
    load_balancer  = "${aws_elb.rancher_ha_https.name}"
    instance_ports = ["80", "81", "8080"]
}
```

with 

```
resource "aws_proxy_protocol_policy" "rancher_ha_http_proxy_policy" {
    count          = "${1 - var.enable_https}"
    load_balancer  = "${aws_elb.rancher_ha_http.name}"
    instance_ports = ["80", "81", "8080"]
}
```

**Comment by nextrevision** [comment]
Thanks for pointing that out! This is now fixed in PR #6
