### ISSUE TITLE
aws_rds_cluster.address attribute error

### ISSUE THREAD

**Issue by jfexyz** [nextrevision/terraform-rancher-ha-example#8]
I might be missing something, but the terraform aws_rds_cluster resource [doesn't seem to have an "address" attribute](https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#attributes-reference). However, [this recent pull request](https://github.com/nextrevision/terraform-rancher-ha-example/pull/7) switched to using it. Maybe it's undocumented, but I get this error when trying to plan a new install: 

```
Error running plan: 1 error(s) occurred:

* module.rancher_aws.data.template_file.install: 1 error(s) occurred:

* module.rancher_aws.data.template_file.install: Resource 'aws_rds_cluster.rancher_ha' does not have attribute 'address' for variable 'aws_rds_cluster.rancher_ha.address'
```

**Comment by nextrevision** [comment]
I reverted that last PR. I definitely see what you are running into. Thanks for letting me know.
